### ISSUE TITLE
This is skidded

### ISSUE THREAD

**Issue by noteason** [NrgCristi/Fortnite-Stuff-Changer#1]
Why is this a literal remix of my code with all the module imports and just random not working shitty parts of my code mushed together skid!!

**Comment by LuxyFN** [comment]
Yes, this is BoogieFN discord bot

**Comment by LuxyFN** [comment]
So skidded

**Comment by LuxyFN** [comment]
WHAT

**Comment by LuxyFN** [comment]
I DIDN'T EDIT
